name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY"
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa_tmp
          chmod 600 ~/.ssh/id_rsa_tmp
          ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST
          cd $DEPLOY_DIR
          git pull origin main
          docker-compose up --build -d
        env:
          DEPLOY_USER: ${{ secrets.USERNAME }}
          DEPLOY_HOST: ${{ secrets.HOST }}
          DEPLOY_KEY: ${{ secrets.PRIVATE_KEY }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}